# Generated by Django 4.0.6 on 2022-07-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='profiles/default_pp.png', null=True, upload_to='media/profiles/'),
        ),
    ]
